// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "jlwarren1": home Resource Client
//
// Command:
// $ goagen
// --design=github.com/jaredwarren/jlwarren1.com/design
// --out=$(GOPATH)/src/github.com/jaredwarren/jlwarren1.com
// --version=v1.3.0

package client

import (
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"os"
	"path"
)

// DownloadStatic downloads /files with the given filename and writes it to the file dest.
// It returns the number of bytes downloaded in case of success.
func (c *Client) DownloadStatic(ctx context.Context, filename, dest string) (int64, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	p := path.Join("/static/", filename)
	u := url.URL{Host: c.Host, Scheme: scheme, Path: p}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return 0, err
	}
	resp, err := c.Client.Do(ctx, req)
	if err != nil {
		return 0, err
	}
	if resp.StatusCode != 200 {
		var body string
		if b, err := ioutil.ReadAll(resp.Body); err != nil {
			if len(b) > 0 {
				body = ": " + string(b)
			}
		}
		return 0, fmt.Errorf("%s%s", resp.Status, body)
	}
	defer resp.Body.Close()
	out, err := os.Create(dest)
	if err != nil {
		return 0, err
	}
	defer out.Close()
	return io.Copy(out, resp.Body)
}

// DownloadJaredWarrenResumePdf downloads JaredWarren-Resume.pdf and writes it to the file dest.
// It returns the number of bytes downloaded in case of success.
func (c *Client) DownloadJaredWarrenResumePdf(ctx context.Context, dest string) (int64, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: "/resume/JaredWarren-Resume.pdf"}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return 0, err
	}
	resp, err := c.Client.Do(ctx, req)
	if err != nil {
		return 0, err
	}
	if resp.StatusCode != 200 {
		var body string
		if b, err := ioutil.ReadAll(resp.Body); err != nil {
			if len(b) > 0 {
				body = ": " + string(b)
			}
		}
		return 0, fmt.Errorf("%s%s", resp.Status, body)
	}
	defer resp.Body.Close()
	out, err := os.Create(dest)
	if err != nil {
		return 0, err
	}
	defer out.Close()
	return io.Copy(out, resp.Body)
}

// DownloadFaviconIco downloads favicon.ico and writes it to the file dest.
// It returns the number of bytes downloaded in case of success.
func (c *Client) DownloadFaviconIco(ctx context.Context, dest string) (int64, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: "/images/favicon.ico"}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return 0, err
	}
	resp, err := c.Client.Do(ctx, req)
	if err != nil {
		return 0, err
	}
	if resp.StatusCode != 200 {
		var body string
		if b, err := ioutil.ReadAll(resp.Body); err != nil {
			if len(b) > 0 {
				body = ": " + string(b)
			}
		}
		return 0, fmt.Errorf("%s%s", resp.Status, body)
	}
	defer resp.Body.Close()
	out, err := os.Create(dest)
	if err != nil {
		return 0, err
	}
	defer out.Close()
	return io.Copy(out, resp.Body)
}

// DownloadKeybaseTxt downloads keybase.txt and writes it to the file dest.
// It returns the number of bytes downloaded in case of success.
func (c *Client) DownloadKeybaseTxt(ctx context.Context, dest string) (int64, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: "/.well-known/keybase.txt"}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return 0, err
	}
	resp, err := c.Client.Do(ctx, req)
	if err != nil {
		return 0, err
	}
	if resp.StatusCode != 200 {
		var body string
		if b, err := ioutil.ReadAll(resp.Body); err != nil {
			if len(b) > 0 {
				body = ": " + string(b)
			}
		}
		return 0, fmt.Errorf("%s%s", resp.Status, body)
	}
	defer resp.Body.Close()
	out, err := os.Create(dest)
	if err != nil {
		return 0, err
	}
	defer out.Close()
	return io.Copy(out, resp.Body)
}

// DashboardHomePath computes a request path to the dashboard action of home.
func DashboardHomePath() string {

	return fmt.Sprintf("/")
}

// Show basic actions
func (c *Client) DashboardHome(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDashboardHomeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDashboardHomeRequest create the request corresponding to the dashboard action endpoint of the home resource.
func (c *Client) NewDashboardHomeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ProfileHomePath computes a request path to the profile action of home.
func ProfileHomePath() string {

	return fmt.Sprintf("/profile")
}

// Set Printer Type
func (c *Client) ProfileHome(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewProfileHomeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewProfileHomeRequest create the request corresponding to the profile action endpoint of the home resource.
func (c *Client) NewProfileHomeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ResumeHomePath computes a request path to the resume action of home.
func ResumeHomePath() string {

	return fmt.Sprintf("/resume")
}

// Single Page Resume
func (c *Client) ResumeHome(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewResumeHomeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewResumeHomeRequest create the request corresponding to the resume action endpoint of the home resource.
func (c *Client) NewResumeHomeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UpdateResumeHomePath computes a request path to the updateResume action of home.
func UpdateResumeHomePath() string {

	return fmt.Sprintf("/resume/update")
}

// Download resume pdf
func (c *Client) UpdateResumeHome(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewUpdateResumeHomeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdateResumeHomeRequest create the request corresponding to the updateResume action endpoint of the home resource.
func (c *Client) NewUpdateResumeHomeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
