version: '3'

services:
  hugo:
    image: jlwarren1/hugo:latest
    build: 
      context: ./hugo
    command: server --bind 0.0.0.0 \
      --source /srv/hugo
      --theme hyde
      --buildDrafts
      --watch
    volumes:
      - ./site:/srv/hugo
    ports:
      - 1313:1313