version: '3'

# Note: check services with: http://localhost:8081/api/rawdata


services:
  traefik:
    image: traefik:v2.0
    ports:
      - 80:80
      - 443:443
      - 1313:1313
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      # - /opt/traefik/certs/:/certs/
      # - ./certs/:/certs/
      # - ./traefik.log:/etc/traefik/traefik.log


      ## TODO: figure out way to push up modules, (docker hub repo?)

  # Restart container, whithout restarting traefik: `docker-compose up -d whoami`
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.jlwarren1.com`) || Path(`/whoami`)"
      - traefik.http.routers.whoami.entryPoints=web
      # - traefik.http.services.whoami.loadbalancer.server.port=80
  
  gotify:
    image: gotify/server
    volumes:
      - ./gotify/data:/app/data
    labels:
      - "traefik.http.routers.gotify.rule=Host(`gotify.jlwarren1.com`)"
      - traefik.http.routers.gotify.entryPoints=web
      - traefik.http.services.gotify.loadbalancer.server.port=80

  keybase:
    image: keybase
    build: 
        context: ./keybase
        # dockerfile: ./keybase/Dockerfile
        args:
            LISTEN_PORT: "8080"
    volumes:
      - ./keybase/static:/go/bin/static
    labels:
      - "traefik.http.routers.keybase.rule=Path(`/.well-known`)"
      - traefik.http.routers.keybase.entryPoints=web
      - traefik.http.services.keybase.loadbalancer.server.port=8080
  
  hugo:
    image: gohugoio/hugo
    labels:
      - traefik.http.routers.blog.rule=Host(`test.jlwarren1.com`, `blog.jlwarren1.com`, `jlwarren1.com:1313`) || Path(`/blog`)
      - traefik.http.routers.blog.entryPoints=web
      - traefik.http.services.blog.loadbalancer.server.port=1313
    # commands:https://gohugo.io/commands/hugo/
    command: server --bind 0.0.0.0
      --baseURL=blog.jlwarren1.com
      --source /srv/hugo
      --theme hyde
      --buildDrafts
      --watch
      --appendPort=false
      --disableLiveReload=true
    volumes:
      - ./blog/site:/srv/hugo