version: '3'

# Note: check services with: http://localhost:8081/api/rawdata


services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "1313:1313"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      # - /opt/traefik/certs/:/certs/
      - ./certs/:/certs/
      # - ./traefik.log:/etc/traefik/traefik.log


      ## TODO: figure out way to push up modules, (docker hub repo?)

  # Restart container, whithout restarting traefik: `docker-compose up -d whoami`
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`) || Path(`/whoami2`)"
      - traefik.http.routers.whoami.entryPoints=web

  hugo:
    image: gohugoio/hugo
    # image: jlwarren1/hugo:latest
    # build: 
      # context: ./blog/hugo
    labels:
      - traefik.http.routers.blog.rule=Host(`blog.localhost`, `localhost:1313`) || Path(`/blog2`)
      - traefik.http.routers.blog.entryPoints=web
      - traefik.http.services.blog.loadbalancer.server.port=1313
      # - traefik.ws.protocol=http
    # commands:https://gohugo.io/commands/hugo/
    command: server --bind 0.0.0.0
      --baseURL=blog.localhost
      --source /srv/hugo
      --theme hyde
      --buildDrafts
      --watch
      --appendPort=false
      --disableLiveReload=true
    volumes:
      - ./blog/site:/srv/hugo
    # ports:
    #   - 1313:1313