version: '3'

# Note: check services with: http://localhost:8081/api/rawdata


services:
  reverse-proxy:
    image: traefik:v2.0
    # command: 
    #   - --api.insecure=true 
    #   - --providers.docker
    ports:
      - "801:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml


      ## TODO: figure out way to push up modules, (docker hub repo?)

  # Restart container, whithout restarting traefik: `docker-compose up -d whoami`
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`) || Path(`/whoami2`)"
  hugo:
    image: jlwarren1/hugo:latest
    build: 
      context: ./blog/hugo
    labels:
      - "traefik.http.routers.whoami.rule=Host(`blog.localhost`) || Path(`/blog`)"
    command: server --bind 0.0.0.0 \
      --source /srv/hugo
      --theme hyde
      --buildDrafts
      --watch
    volumes:
      - ./blog/site:/srv/hugo
    ports:
      - 1313:1313