version: '3'

# Note: check services with: http://localhost:8081/api/rawdata


services:
  reverse-proxy:
    image: traefik:v2.0
    command: 
      - --api.insecure=true 
      - --providers.docker
    ports:
      - "801:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


      ## TODO: figure out way to push up modules, (docker hub repo?)

  # Restart container, whithout restarting traefik: `docker-compose up -d whoami`
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`) || Path(`/whoami2`)"
  whoami3:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami3.rule=Host(`whoam3.localhost`) || Path(`/whoami3`)"