
## Static configuration
entryPoints:
  web:
   address: ":80"
  websecure:
    address: ":443"
  web-test:
   address: ":8081"
  blog:
   address: ":1313"

api:
  insecure: true
  dashboard: true

providers:
  docker: {}

accessLog: {}

log:
  filePath: "./traefik.log"

serversTransport:
  insecureSkipVerify: true
  # rootCAs:
  #   - /mycert.cert

tls:
  certificates:
    - certFile: /cert/bladehq.com.crt
      keyFile: /cert/bladehq.com.key

# Latency Check
http:
  middlewares:
    latency-check:
      circuitBreaker:
        expression: "LatencyAtQuantileMS(50.0) > 100"