baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Jared Warren"

[params]
    description = "About Me"


[[menu.main]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "/about/"