// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "jlwarren1": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/jaredwarren/jlwarren1.com/design
// --out=$(GOPATH)/src/github.com/jaredwarren/jlwarren1.com
// --version=v1.3.0

package app
