// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "jlwarren1": Application User Types
//
// Command:
// $ goagen
// --design=github.com/jaredwarren/jlwarren1.com/design
// --out=$(GOPATH)/src/github.com/jaredwarren/jlwarren1.com
// --version=v1.2.0-dirty

package app
