baseURL = "//blog.localhost"
languageCode = "en-us"
title = "Jared Warren"
# relativeURLs = false

[params]
    description = "About Me"


[[menu.main]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "/about/"